// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/22/2026, 4:33:58 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/root/.openclaw/workspace/nuevostec-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/.openclaw/workspace/nuevostec-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/.openclaw/workspace/nuevostec-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/.openclaw/workspace/nuevostec-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/.openclaw/workspace/nuevostec-web/plugins/**/*.{js,ts,mjs}","/root/.openclaw/workspace/nuevostec-web/composables/**/*.{js,ts,mjs}","/root/.openclaw/workspace/nuevostec-web/utils/**/*.{js,ts,mjs}","/root/.openclaw/workspace/nuevostec-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/.openclaw/workspace/nuevostec-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/root/.openclaw/workspace/nuevostec-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/root/.openclaw/workspace/nuevostec-web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;